kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: threescaleapi-operator
rules:
- apiGroups:
  - 3scale.net
  resources:
  - apis
  verbs:
  - "*"
- apiGroups: [""]
  resources:
  - services
  verbs:
  - "*"
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: threescaleapi-account
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: threescaleapi-operator
  apiGroup: rbac.authorization.k8s.io
