version: "3.7"
services:

  envoy:
    build:
      context: envoy
      dockerfile: Dockerfile
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml
    networks:
      - envoymesh
    environment:
      LOG_LEVEL: debug
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  app:
    build:
      context: app
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - app
    expose:
      - "8080"

  ext-auth:
    build:
      context: auth-ruby
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - auth
    expose:
      - "50051"

  rate-limit:
    image: quay.io/3scale/limitador:latest
    environment:
      HOST: "0.0.0.0"
      PORT: 50052
    networks:
      envoymesh:
        aliases:
          - limitador
    expose:
      - "50052"


networks:
  envoymesh: {}
