apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostia-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ostia-operator
  template:
    metadata:
      labels:
        name: ostia-operator
    spec:
      containers:
        - name: ostia-operator
          image: quay.io/3scale/ostia-operator:master
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - ostia-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "ostia-operator"
