kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ostia-operator
rules:
- apiGroups:
  - ostia.3scale.net
  resources:
  - apis
  verbs:
  - "*"
- apiGroups: [""]
  resources:
  - services
  verbs:
  - "*"
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  - deploymentconfigs/scale
  - deploymentconfigs/status
  verbs:
  - "*"
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - "*"
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ostia-account-ostia-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: ostia-operator
  apiGroup: rbac.authorization.k8s.io
