version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.4
        environment:
          OPERATOR_SDK_VERSION: 0.7.0
    working_directory: /go/src/github.com/3scale/ostia
    steps:

      - setup_remote_docker:
          reusable: true
          exclusive: false

      - checkout

      - restore_cache:
          keys:
            - v1-ostia-vendor-{{ arch }}-sdk-0.7.0-{{ checksum "ostia-operator/Gopkg.lock" }}
            - v1-ostia-vendor-{{ arch }}-sdk-0.7.0-{{ .Branch }}
      - run:
          name: Install dependencies
          working_directory: ostia-operator
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            curl -L https://github.com/operator-framework/operator-sdk/releases/download/v${OPERATOR_SDK_VERSION}/operator-sdk-v${OPERATOR_SDK_VERSION}-x86_64-linux-gnu -o /go/bin/operator-sdk
            chmod +x /go/bin/operator-sdk

            dep check || dep ensure -v

      - save_cache:
          key: v1-ostia-vendor-{{ arch }}-sdk-0.7.0-{{ checksum "ostia-operator/Gopkg.lock" }}
          paths:
            - "/go/src/github.com/3scale/ostia/ostia-operator/vendor"
            - "/go/pkg"

      - run:
          name: Build ostia-operator
          working_directory: ostia-operator
          command: |
              make build NAMESPACE=172.30.1.1:5000/openshift VERSION=test

      - run:
          name: Run unit tests
          working_directory: ostia-operator
          command: |
              make unit

      - run:
          name: Sharing requirements to downstream job
          command: |
            mkdir -p /tmp/ostia-reqs/image /tmp/ostia-reqs/deploy /tmp/ostia-reqs/test
            docker save -o /tmp/ostia-reqs/image/image.tar 172.30.1.1:5000/openshift/ostia-operator:test
            cp -vr ostia-operator/{deploy,test,Makefile} /tmp/ostia-reqs/

      - persist_to_workspace:
          root: /tmp/ostia-reqs
          paths:
            - Makefile
            - deploy
            - image
            - test

  test:
    machine: true
    working_directory: /tmp
    environment:
      IMAGE: 172.30.1.1:5000/openshift/ostia-operator:test
    steps:

      - attach_workspace:
          at: /tmp/ostia-reqs

      - run:
          name: Install OpenShift Client Tools
          command: |
            curl -L https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz \
            | tar --strip-components=1 -xz -C .
            sudo mv -v oc kubectl /usr/local/bin/

      - run:
          name: Configure Docker
          command: |
            echo '{"insecure-registries": ["172.30.0.0/16"]}' | sudo tee --append /etc/docker/daemon.json
            sudo service docker restart

      - run:
          name: Start and Configure OpenShift Cluster
          working_directory: /tmp/ostia-reqs/test
          command: |
            # echo "export OPENSHIFT_IP=$(ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')" >> $BASH_ENV
            echo "export OPENSHIFT_IP=127.0.0.1" >> $BASH_ENV
            source $BASH_ENV
            oc cluster up \
              --public-hostname=${OPENSHIFT_IP} \
              --enable='*' --enable=-centos-imagestreams --enable=-sample-templates
            oc login -u system:admin --insecure-skip-tls-verify=true > /dev/null
            oc adm policy add-cluster-role-to-user cluster-admin developer > /dev/null
            oc login -u developer --insecure-skip-tls-verify=true > /dev/null

      - run:
          name: Unpack and push ostia-operator to internal registry
          working_directory: /tmp/ostia-reqs/image
          command: |
            docker load -i image.tar
            source /tmp/ostia-reqs/test/tests/common/common.sh; wait_for_pod_ready deploymentconfig docker-registry default
            docker login -u developer -p $(oc whoami -t) 172.30.1.1:5000
            docker push "${IMAGE}"

      - run:
          name: Run integration tests
          working_directory: /tmp/ostia-reqs/
          command: |
            make integration OPENSHIFT_PUBLIC_HOSTNAME="${OPENSHIFT_IP}.nip.io" IMAGE="${IMAGE}"


workflows:
  version: 2
  build_and_test_integration:
    jobs:
      - build
      - test:
          requires:
            - build
