localhost:8000:
  enabled: true

  identity:
    - oidc:
        name: test
        endpoint: http://localhost:8080/auth/realms/test

    - oidc:
        name: demo
        endpoint: https://localhost:8443/realms/demo/

    - oidc:
        name: admin
        endpoint: https://localhost:8443/realms/admin/

  metadata:
    - userinfo:
        oidc: test
        client_id: test
        client_secret: test

  authorization:
    - opa:
        endpoint: http://localhost:8181/v1/data/ostia/authz/localhost
        rego: |
          allow {
            input.method == "GET"
            input.path = ["pets"]
          }

          allow {
            input.method == "POST"
            input.path = ["pets"]
            input.context.identity.roles[_] == "admin"
          }
    - jwt:
        match:
          http:
            path: '/api/*'
        claim:
          aud: api
