localhost:8000:
  enabled: true

  identity:
    - oidc:
          name: master
          endpoint: http://localhost:8080/auth/realms/master
          client_id: master

    - oidc:
        name: demo
        endpoint: https://localhost:8443/realms/demo/

    - oidc:
        name: admin
        endpoint: https://localhost:8443/realms/admin/

  authorization:
    - opa:
        rego: |
          allow {
            input.method == "PUT"
            some petid
            input.path = ["pets", petid]
            input.user == input.owner
          }
    - jwt:
        match:
          http:
            path: '/api/*'
        claim:
          aud: api
