localhost:8000:
  enabled: true

  identity:
    - oidc:
        name: test
        endpoint: http://localhost:8080/auth/realms/test

    - oidc:
        name: demo
        endpoint: https://localhost:8443/realms/demo/

    - oidc:
        name: admin
        endpoint: https://localhost:8443/realms/admin/

  metadata:
    - userinfo:
        oidc: test
        client_id: test
        client_secret: test

  authorization:
    - opa:
        uuid: 8fa79d93-0f93-4e23-8c2a-666be266cad1
        rego: |
          allow {
            http_request.method == "GET"
            path_arr = ["pets"]
          }

          allow {
            http_request.method == "POST"
            path_arr = ["pets"]
          }

          allow {
            http_request.method == "GET"
            own_resource
          }

          allow {
            http_request.method == "PUT"
            own_resource
          }

          allow {
            http_request.method == "DELETE"
            own_resource
          }

          allow {
            http_request.method == "GET"
            path_arr = ["pets", "stats"]
            is_admin
          }

          own_resource {
            some petid
            path_arr = ["pets", petid]
            subject := object.get(identity, "sub", object.get(identity, "username", ""))
            subject == object.get(resource, "owner", "")
          }

          is_admin {
            metadata.user_info.roles[_] == "admin"
          }
    - jwt:
        enabled: false
        match:
          http:
            path: '/api/*'
        claim:
          aud: api
