apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apis.ostia.3scale.net
spec:
  group: ostia.3scale.net
  versions:
    - name: v1alpha1
      served: true
      storage: false
    - name: v2alpha1
      served: true
      storage: true
  names:
    kind: API
    listKind: APIList
    plural: apis
    singular: api
  scope: Namespaced
  subresources:
    status: {}