apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servers.ostia.3scale.net
spec:
  group: ostia.3scale.net
  versions:
    - name: v2alpha1
      served: true
      storage: true
  names:
    kind: Server
    listKind: ServerList
    plural: servers
    singular: server
  scope: Namespaced
  subresources:
    status: {}