apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostia-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ostia-operator
  template:
    metadata:
      labels:
        name: ostia-operator
    spec:
      serviceAccountName: ostia-operator
      containers:
        - name: ostia-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - ostia-operator
          - --zap-devel
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ostia-operator"
